### ISSUE TITLE
FE - NavBar Implementation

### ISSUE THREAD

**Issue by ccelest1** [ylopez25/Tech-dive#27]
- [ ] User should be able to navigate between Admin and Exams section

**Comment by Benjamin-Ortiz** [comment]
Before I can approve: 
- [x] Comment out the search feature (It's considered a dead link at the moment aka it does nothing/takes us nowhere)
        - An issue/card should be made for the search feature in near future, which in turn involves either a same page filter or a '/searchResults' page .
- [x] The docs/video example doesn't mention using '/', have the "Logo" redirect to '/exams/' which is our root page for now until MVP completion
        - A Home page is a great Idea after priorities are met, when that time comes we can brainstorm!

**Comment by ccelest1** [comment]
@Benjamin-Ortiz I’ll be working on the landing page it shouldn’t be too difficult nor does it have to be that intricate. I believe we will be able to make priorities.
@ylopez25 we can save search for now I will try to work on it
